# configs/config.yaml
defaults:
  - train: train
  - data: data
  - model: resnet50
  - optimizer: adamw
  - _self_
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
